extends SceneTree


func _initialize() -> void:
	var lines := PackedStringArray()
	lines.append("Aegis of Ember - Godot Engine and Third-Party Copyright Notices")
	lines.append("Generated by Godot %s from Engine license metadata." % Engine.get_version_info().get("string", "unknown"))
	lines.append("")
	lines.append("GODOT ENGINE LICENSE")
	lines.append("====================")
	lines.append(Engine.get_license_text())
	lines.append("")
	lines.append("THIRD-PARTY COPYRIGHTS")
	lines.append("======================")
	for component_value in Engine.get_copyright_info():
		var component: Dictionary = component_value
		lines.append("")
		lines.append(str(component.get("name", "Unnamed component")))
		lines.append("-".repeat(lines[-1].length()))
		for part_value in component.get("parts", []):
			var part: Dictionary = part_value
			for file_pattern in part.get("files", []):
				lines.append("Files: " + str(file_pattern))
			for copyright_line in part.get("copyright", []):
				lines.append("Copyright: " + str(copyright_line))
			lines.append("License: " + str(part.get("license", "unknown")))
	var license_info: Dictionary = Engine.get_license_info()
	var license_names: Array = license_info.keys()
	license_names.sort()
	lines.append("")
	lines.append("THIRD-PARTY LICENSE TEXTS")
	lines.append("=========================")
	for license_name in license_names:
		lines.append("")
		lines.append(str(license_name))
		lines.append("-".repeat(str(license_name).length()))
		lines.append(str(license_info[license_name]))
	var output_directory := ProjectSettings.globalize_path("res://release")
	var directory_error := DirAccess.make_dir_recursive_absolute(output_directory)
	if directory_error != OK and directory_error != ERR_ALREADY_EXISTS:
		push_error("Cannot create release notice directory")
		quit(1)
		return
	var file := FileAccess.open("res://release/GODOT_COPYRIGHT.txt", FileAccess.WRITE)
	if file == null:
		push_error("Cannot write Godot copyright notices")
		quit(1)
		return
	var output_text := "\n".join(lines).strip_edges(false, true) + "\n"
	file.store_string(output_text)
	file.flush()
	print("Godot copyright notices written for %s" % Engine.get_version_info().get("string", "unknown"))
	quit(0)
